### ISSUE TITLE
`TencentChannelInfoImpl` 反序列化失败

### ISSUE THREAD

**Issue by ForteScarlet** [simple-robot/simbot-component-qq-guild#44]
```log
2022-07-27T05:11:11.536Z ERROR  --- [tDispatcher-worker-9]                   l.f.s.t.b.1.[0,1]  : Pre processing failed.
kotlinx.serialization.MissingFieldException: Fields [position, parent_id] are required for type with serial name 'love.forte.simbot.tencentguild.internal.TencentChannelInfoImpl', but they were missing
        at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
        at love.forte.simbot.tencentguild.internal.TencentChannelInfoImpl.<init>(TencentChannelInfoImpl.kt:28)
        at love.forte.simbot.tencentguild.internal.TencentChannelInfoImpl.<init>(TencentChannelInfoImpl.kt)
        at love.forte.simbot.tencentguild.internal.TencentChannelInfoImpl$$serializer.deserialize(TencentChannelInfoImpl.kt:28)
        at love.forte.simbot.tencentguild.internal.TencentChannelInfoImpl$$serializer.deserialize(TencentChannelInfoImpl.kt:28)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
        at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
        at love.forte.simbot.tencentguild.core.internal.TencentGuildBotImpl$processEvent$3$lazy$1.invoke(TencentGuildBotImpl.kt:443)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at love.forte.simbot.tencentguild.core.internal.TencentGuildBotImpl$processEvent$3$lazyDecoded$1.get(TencentGuildBotImpl.kt:444)
        at kotlin.jvm.internal.PropertyReference0.invoke(PropertyReference0.java:35)
        at love.forte.simbot.component.tencentguild.internal.TencentGuildComponentBotEventProcessKt.onChannelDelete(TencentGuildComponentBotEventProcess.kt:141)
        at love.forte.simbot.component.tencentguild.internal.TencentGuildComponentBotEventProcessKt.access$onChannelDelete(TencentGuildComponentBotEventProcess.kt:1)
        at love.forte.simbot.component.tencentguild.internal.TencentGuildComponentBotEventProcessKt$registerEventPreProcessor$1.invokeSuspend(TencentGuildComponentBotEventProcess.kt:47)
        at love.forte.simbot.component.tencentguild.internal.TencentGuildComponentBotEventProcessKt$registerEventPreProcessor$1.invoke(TencentGuildComponentBotEventProcess.kt)
        at love.forte.simbot.component.tencentguild.internal.TencentGuildComponentBotEventProcessKt$registerEventPreProcessor$1.invoke(TencentGuildComponentBotEventProcess.kt)
        at love.forte.simbot.tencentguild.core.internal.TencentGuildBotImpl$processEvent$3.invokeSuspend(TencentGuildBotImpl.kt:447)
        at love.forte.simbot.tencentguild.core.internal.TencentGuildBotImpl$processEvent$3.invoke(TencentGuildBotImpl.kt)
        at love.forte.simbot.tencentguild.core.internal.TencentGuildBotImpl$processEvent$3.invoke(TencentGuildBotImpl.kt)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
        at love.forte.simbot.tencentguild.core.internal.TencentGuildBotImpl$processEvent$$inlined$mapNotNull$1$2.emit(Emitters.kt:245)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by ForteScarlet** [comment]
重构后可能不在存在此问题
